import Avatar from '@/assets/image/avatar.jpeg'

const BasicInformation = [
  {
    label: '基本信息',
    children: [
      {
        label: '商户账号',
        name: 'account',
        type: 'readonly',
      },
      {
        label: '商户名称',
        name: 'account',
        type: 'readonly',
      },
      {
        label: '联系电话',
        name: 'account',
        reg: 'tel',
      },
      {
        label: '商家邮箱',
        name: 'account',
        reg: 'email',
      },
      {
        label: '团购快递收货超时时间',
        name: 'account',
        reg: 'date',
      },
      {
        label: '线下支付权限',
        name: 'account',
      },
      {
        label: '商户经纬度',
        name: 'account',
      },
      {
        label: '微官网点击量',
        name: 'account',
      },
      {
        label: '商户所属分类',
        name: 'account',
      },
    ],
  },
  {
    label: '商家描述',
    children: [
      {
        label: '商户描述',
        name: 'account',
      },
      {
        label: '商户图片',
        name: 'account',
      },
      {
        label: '商户详情',
        name: 'account',
      },
    ],
  },
  {
    label: '绑定微信',
    children: [
      {
        label: '绑定微信',
        name: 'account',
      },
    ],
  },
]

const RedEnvelopeListData = [
  {
    id: 1,
    name: '小程序红包测试1',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 2,
    name: '小程序红包测试2',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 3,
    name: '小程序红包测试3',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 4,
    name: '小程序红包测试4',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 5,
    name: '小程序红包测试5',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 6,
    name: '小程序红包测试6',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
]

const StoreList = [
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
]

const StoreCategoryData = [
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
]

const PreferentialData = [
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
  {
    type: '新单',
    amount: 11000,
    preferential: 21.2,
    status: '启用',
  },
]

const CommodityData = [
  {
    title: '10.29测试电商余额支付-引流佣金（100元）',
    img: Avatar,
    saler: 10000,
    status: '在售',
    saled: 235,
  },
  {
    title: '10.29测试电商余额支付-引流佣金（100元）',
    img: Avatar,
    saler: 10000,
    status: '在售',
    saled: 235,
  },
  {
    title: '10.29测试电商余额支付-引流佣金（100元）',
    img: Avatar,
    saler: 10000,
    status: '在售',
    saled: 235,
  },
  {
    title: '10.29测试电商余额支付-引流佣金（100元）',
    img: Avatar,
    saler: 10000,
    status: '在售',
    saled: 235,
  },
  {
    title: '10.29测试电商余额支付-引流佣金测试测试测试测试（100元）',
    img: Avatar,
    saler: 10000,
    status: '在售',
    saled: 235,
  },
  {
    title: '10.29测试电商余额支付-引流佣金（100元）',
    img: Avatar,
    saler: 10000,
    status: '在售',
    saled: 235,
  },
]

const AppletsData = [
  {
    no: 234,
    tel: '****',
    sex: '未知',
    nickName: '超级会员',
    createTime: '2019-04-26',
    img: Avatar,
  },
  {
    no: 234,
    tel: '****',
    sex: '未知',
    nickName: '超级会员',
    createTime: '2019-04-26',
    img: Avatar,
  },
  {
    no: 234,
    tel: '****',
    sex: '未知',
    nickName: '超级会员',
    createTime: '2019-04-26',
    img: Avatar,
  },
  {
    no: 234,
    tel: '****',
    sex: '未知',
    nickName: '超级会员',
    createTime: '2019-04-26',
    img: Avatar,
  },
  {
    no: 234,
    tel: '****',
    sex: '未知',
    nickName: '超级会员',
    createTime: '2019-04-26',
    img: Avatar,
  },
  {
    no: 234,
    tel: '****',
    sex: '未知',
    nickName: '超级会员',
    createTime: '2019-04-26',
    img: Avatar,
  },
]

const MemberCardData = [
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
  {
    id: 6,
    comment: '现金',
    discount: 3,
    name: '现金卡',
    usercount: 17,
  },
]

const userData = [
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
  {
    id: 213234,
    nickName: 'fetch',
    img: Avatar,
  },
]

const couponData = [
  {
    id: 12,
    type: '预定',
    system: '移动网页 App 微信',
    name: '预约打死喉结',
    category: '司仪预约',
    total: 100,
    newUser: '否',
    startTime: '2019-07-07',
    entTime: '2019-10-10',
    condition: '满100.00 减 10.0 元',
    used: 4,
    Expired: true,
    img: Avatar,
  },
  {
    id: 12,
    type: '预定',
    system: '移动网页 App 微信',
    name: '预约打死喉结',
    category: '司仪预约',
    total: 100,
    newUser: '否',
    startTime: '2019-07-07',
    entTime: '2019-10-10',
    condition: '满100.00 减 10.0 元',
    used: 4,
    Expired: true,
    img: Avatar,
  },
  {
    id: 12,
    type: '预定',
    system: '移动网页 App 微信',
    name: '预约打死喉结',
    category: '司仪预约',
    total: 100,
    newUser: '否',
    startTime: '2019-07-07',
    entTime: '2019-10-10',
    condition: '满100.00 减 10.0 元',
    used: 4,
    Expired: true,
    img: Avatar,
  },
  {
    id: 12,
    type: '预定',
    system: '移动网页 App 微信',
    name: '预约打死喉结',
    category: '司仪预约',
    total: 100,
    newUser: '否',
    startTime: '2019-07-07',
    entTime: '2019-10-10',
    condition: '满100.00 减 10.0 元',
    used: 4,
    Expired: true,
    img: Avatar,
  },
  {
    id: 12,
    type: '预定',
    system: '移动网页 App 微信',
    name: '预约打死喉结',
    category: '司仪预约',
    total: 100,
    newUser: '否',
    startTime: '2019-07-07',
    entTime: '2019-10-10',
    condition: '满100.00 减 10.0 元',
    used: 4,
    Expired: true,
    img: Avatar,
  },
  {
    id: 12,
    type: '预定',
    system: '移动网页 App 微信',
    name: '预约打死喉结',
    category: '司仪预约',
    total: 100,
    newUser: '否',
    startTime: '2019-07-07',
    entTime: '2019-10-10',
    condition: '满100.00 减 10.0 元',
    used: 4,
    Expired: true,
    img: Avatar,
  },
]

export {
  BasicInformation,
  RedEnvelopeListData,
  StoreList,
  StoreCategoryData,
  PreferentialData,
  CommodityData,
  AppletsData,
  MemberCardData,
  userData,
  couponData,
}
