import Avatar from '@/assets/image/avatar.jpeg'

const BasicInformation = [
  {
    label: '基本信息',
    children: [
      {
        label: '商户账号',
        name: 'account',
        type: 'readonly',
      },
      {
        label: '商户名称',
        name: 'account',
        type: 'readonly',
      },
      {
        label: '联系电话',
        name: 'account',
        reg: 'tel',
      },
      {
        label: '商家邮箱',
        name: 'account',
        reg: 'email',
      },
      {
        label: '团购快递收货超时时间',
        name: 'account',
        reg: 'date',
      },
      {
        label: '线下支付权限',
        name: 'account',
      },
      {
        label: '商户经纬度',
        name: 'account',
      },
      {
        label: '微官网点击量',
        name: 'account',
      },
      {
        label: '商户所属分类',
        name: 'account',
      },
    ],
  },
  {
    label: '商家描述',
    children: [
      {
        label: '商户描述',
        name: 'account',
      },
      {
        label: '商户图片',
        name: 'account',
      },
      {
        label: '商户详情',
        name: 'account',
      },
    ],
  },
  {
    label: '绑定微信',
    children: [
      {
        label: '绑定微信',
        name: 'account',
      },
    ],
  },
]

const RedEnvelopeListData = [
  {
    id: 1,
    name: '小程序红包测试1',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 2,
    name: '小程序红包测试2',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 3,
    name: '小程序红包测试3',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 4,
    name: '小程序红包测试4',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 5,
    name: '小程序红包测试5',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
  {
    id: 6,
    name: '小程序红包测试6',
    prizeTotal: 400,
    prize: 2,
    maxNum: 5,
    minNum: 1,
    canTake: 5,
    taked: 2,
    status: '已下架',
    Browse: 2,
    startTime: '2019-07-11 13:15:00',
    endTime: '2019-10-14 10:23:15',
  },
]

const StoreList = [
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
  {
    title: '是三十九分',
    img: Avatar,
    status: '正常',
    fl: '/',
    yh: '/',
    bj: '/',
    tj: '/',
  },
]

const StoreCategoryData = [
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
  {
    title: '水果',
    day: ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
    management: '/',
    modify: '/',
  },
]

export {
  BasicInformation, RedEnvelopeListData, StoreList, StoreCategoryData,
}
